authors: 
  - Leon Meguira (@leonmeguira)
  - Nati Fridman (@natifridman)
  - Nofar Kovalsky-Livkind (@Nofarliv)
  - Michal Greenberg (@micahlg)
  - Ofer Epstein (@ofere)
dependencies: {}
description: A collection of Ansible Modules for Radware devices
documentation: ''
homepage: https://www.radware.com
issues: https://github.com/Radware/radware-ansible/issues
license_file: 'COPYING'
name: radware_modules
namespace: radware
readme: README.md
repository: https://github.com/Radware/radware-ansible
tags: 
- radware
- alteon
- cloud
- collection
- networking
- sdn
version: 0.4.12

